### DISCUSSION TITLE
Failing to exclude all resources from a specific resource group

### DISCUSSION THREAD

**Discussion by steveliakakos-dstl** [ekristen/azure-nuke#95] [Q&A]
Hi there, I'm struggling to get a config that ignores all resources in a specific resource group. That is, I don't want azure-nuke to touch that resource group or anything in it.

I have a config file a bit like this:
```
---
regions:
  - uksouth
  - ukwest
  - global

__global__:
  - property: ResourceGroup
    value: "RGtoKeep"

accounts:
  #########:
    filters:
      ResourceGroup:
        - "RGtoKeep"
```

However, I'm still getting resources listed as **would remove** that belong to RGtoKeep:
```
uksouth - KeyVault - somekeyvault - [Name: "somekeyvault", Region: "uksouth", ResourceGroup: "RGtoKeep", SubscriptionID: "#########"] - would remove
```

What am I missing?

**Comment by ekristen** [comment]
Hi @steveliakakos-dstl filters are based on resource type, not on properties and `__global__` is a special resource type.

```yaml
regions:
  - uksouth
  - ukwest
  - global

accounts:
  #########:
    filters:
      __global__:
        - property: ResourceGroup
          value: "RGtoKeep"
```

OR

```yaml
regions:
  - uksouth
  - ukwest
  - global

accounts:
  #########:
    filters:
      KeyVault:
        - property: ResourceGroup
          value: "RGtoKeep"
```
