### ISSUE TITLE
started getting an error - "scanner is already registered, you cannot register it twice"

### ISSUE THREAD

**Issue by yuval-katzman-digsec** [ekristen/azure-nuke#105]
azure-nuke nuke --config=./tenant_config.yaml --force-sleep 3 --no-prompt --tenant-id REDACTED --client-id *** --client-secret ***

config:
```
regions:
  - all
blocklist:
  - redacted
accounts:
  redacted:
    presets:
      - clean
resource-types:
  includes:
    - ResourceGroup
    - StorageAccount
    - VirtualMachine
    - ComputeSnapshot
    - ContainerRegistry
    - Disk
    - ManagementLock
    - VirtualNetwork
    - NetworkInterface
    - NetworkSecurityGroup
    - PublicIPAddress
presets:
  clean:
    filters:
      __global__:
        - property: tag:redacted
          value: 'true'
        - property: tag:redacted
          value: redacted
      ResourceGroup:
        - property: Name
          type: glob
          value: redacted-*
      StorageAccount:
        - property: Name
          type: glob
          value: redacted*
      ManagementLock:
        - property: ResourceGroup
          type: contains
          value: redacted
```

the tool is v.1.2.0, installed via brew into a github actions automated process.
by the way, interestingly, when I execute the process from another branch, it works. only our "main" branch has this issue.

@ekristen what am I missing here? do I need to delete something on the subscription / tenant level for it to work now?
I'm able to execute the tool locally with the same exact credentials without any issues
